-- Auto-generated by crop-images.js
-- Run this in your Supabase SQL Editor AFTER running schema.sql

DELETE FROM questions;

INSERT INTO questions (fragment_url, correct_answer, options, category) VALUES
  ('/fragments/frag_jomok13.webp', 'Ape tu woi', ARRAY['Nak Ikot', 'Amba Remaja', 'Aku Bilangin ke Polisi😡', 'Ape tu woi'], 'suki'),
  ('/fragments/frag_jomok14.webp', 'Mas Amba', ARRAY['Duh Ketahuan', 'Awas Gw Lagi Sigma', 'Amba Remaja', 'Mas Amba'], 'suki'),
  ('/fragments/frag_jomok15.webp', 'Kanaratzu Katsu', ARRAY['Mas Amba😡', 'AmbaTron', 'Mas Amba', 'Kanaratzu Katsu'], 'suki'),
  ('/fragments/frag_jomok16.webp', 'Kontol Emosimu Kawan', ARRAY['Alamak', 'Banyak Omong Lu Suki', 'Sebaiknya Jangan Terlalu Gegabah', 'Kontol Emosimu Kawan'], 'suki'),
  ('/fragments/frag_jomok17.webp', 'Awas Gw Lagi Sigma', ARRAY['Ngab Owi', 'Mas Amba😎', 'Awas Gw Lagi Sigma', 'AmbaTron'], 'suki'),
  ('/fragments/frag_jomok18.webp', 'Sebaiknya Jangan Terlalu Gegabah', ARRAY['Ape tu woi', 'Ngab Owi', 'Mas Amba😎', 'Sebaiknya Jangan Terlalu Gegabah'], 'suki'),
  ('/fragments/frag_jomok19.webp', 'Mas Amba😎', ARRAY['Ape tu woi', 'Aku Bilangin ke Polisi😡', 'Mas Rusdi😎', 'Mas Amba😎'], 'suki'),
  ('/fragments/frag_jomok23.webp', 'Mas Amba😡', ARRAY['Sebaiknya Jangan Terlalu Gegabah', 'Mas Rusdi😎', 'Ngab Owi', 'Mas Amba😡'], 'suki'),
  ('/fragments/frag_jomok21.webp', 'Banyak Omong Lu Suki', ARRAY['Mas Rusdi😎', 'Banyak Omong Lu Suki', 'Ape tu woi', 'Duh Ketahuan'], 'suki'),
  ('/fragments/frag_jomok22.webp', 'Nak Ikot', ARRAY['Aku Bilangin ke Polisi😡', 'Halah Nyocot', 'Amba Remaja', 'Nak Ikot'], 'suki'),
  ('/fragments/frag_jomok24.webp', 'Alamak', ARRAY['Alamak', 'Sebaiknya Jangan Terlalu Gegabah', 'Mas Rusdi😎', 'Kontol Emosimu Kawan'], 'suki'),
  ('/fragments/frag_jomok25.webp', 'Aku Bilangin ke Polisi😡', ARRAY['Ngab Owi', 'Mas Rusdi😎', 'Nak Ikot', 'Aku Bilangin ke Polisi😡'], 'suki'),
  ('/fragments/frag_jomok26.webp', 'Duh Ketahuan', ARRAY['Duh Ketahuan', 'Mas Amba', 'Kontol Emosimu Kawan', 'AmbaTron'], 'suki'),
  ('/fragments/frag_jomok27.webp', 'Tak Bosan Bosan Aku Menunggumu', ARRAY['Amba Remaja', 'Alamak', 'Duh Ketahuan', 'Tak Bosan Bosan Aku Menunggumu'], 'suki'),
  ('/fragments/frag_jomok28.webp', 'Mas Fuad Sparta', ARRAY['Nak Ikot', 'Mas Rusdi😎', 'Mas Fuad Sparta', 'Mas Amba😎'], 'suki'),
  ('/fragments/frag_jomok29.webp', 'Halah Nyocot', ARRAY['Mas Fuad Sparta', 'Mas Amba😡', 'Tak Bosan Bosan Aku Menunggumu', 'Halah Nyocot'], 'suki'),
  ('/fragments/frag_jomok30.webp', 'Mas Rusdi😎', ARRAY['Amba Remaja', 'Mas Rusdi😎', 'Mas Amba', 'Duh Ketahuan'], 'suki'),
  ('/fragments/frag_jomok32.webp', 'Ngab Owi', ARRAY['Ngab Owi', 'Mas Amba😡', 'Awas Gw Lagi Sigma', 'Banyak Omong Lu Suki'], 'suki'),
  ('/fragments/frag_jomok33.webp', 'Amba Remaja', ARRAY['Nak Ikot', 'Banyak Omong Lu Suki', 'Amba Remaja', 'Duh Ketahuan'], 'suki'),
  ('/fragments/frag_jomok34.webp', 'AmbaTron', ARRAY['Mas Amba😎', 'AmbaTron', 'Tak Bosan Bosan Aku Menunggumu', 'Mas Amba'], 'suki'),
  ('/fragments/frag_jomok1.webp', 'Bersiaplah', ARRAY['Yang Nanya Siapa😂', 'Bersiaplah', 'Tertawa Tapi Terluka😂', 'Sedang Sibuk'], 'jomok'),
  ('/fragments/frag_jomok2.webp', 'Berotak Kontol', ARRAY['Sedang Sibuk', 'Dikira Lucu😐', 'Tertawa Tapi Terluka😂', 'Berotak Kontol'], 'jomok'),
  ('/fragments/frag_jomok3.webp', 'Rusdi', ARRAY['Sedang Sibuk', 'Berotak Kontol', 'Ada Ada Saja🤣', 'Rusdi'], 'jomok'),
  ('/fragments/frag_jomok4.webp', 'Gw Lagi Yang Kena', ARRAY['Dikira Lucu😐', 'Gk', 'Gw Lagi Yang Kena', 'Rusdi'], 'jomok'),
  ('/fragments/frag_jomok5.webp', 'Langsung Sigma Gw Bjiir😂😂', ARRAY['Berotak Kontol', 'Dikira Lucu😐', 'Langsung Sigma Gw Bjiir😂😂', 'Aku Nak'], 'jomok'),
  ('/fragments/frag_jomok6.webp', 'Gk', ARRAY['Dikira Lucu😐', 'Tertawa Tapi Terluka😂', 'Gk', 'Aku Nak'], 'jomok'),
  ('/fragments/frag_jomok7.webp', 'Sedang Sibuk', ARRAY['Sedang Sibuk', 'Gk', 'Rusdi', 'Bersiaplah'], 'jomok'),
  ('/fragments/frag_jomok8.webp', 'Aku Nak', ARRAY['Ada Ada Saja🤣', 'Tertawa Tapi Terluka😂', 'Aku Nak', 'Dikira Lucu😐'], 'jomok'),
  ('/fragments/frag_jomok9.webp', 'Yang Nanya Siapa😂', ARRAY['Bersiaplah', 'Gw Lagi Yang Kena', 'Yang Nanya Siapa😂', 'Aku Nak'], 'jomok'),
  ('/fragments/frag_jomok10.webp', 'Dikira Lucu😐', ARRAY['Ada Ada Saja🤣', 'Dikira Lucu😐', 'Gw Lagi Yang Kena', 'Sedang Sibuk'], 'jomok'),
  ('/fragments/frag_jomok11.webp', 'Ada Ada Saja🤣', ARRAY['Aku Nak', 'Dikira Lucu😐', 'Langsung Sigma Gw Bjiir😂😂', 'Ada Ada Saja🤣'], 'jomok'),
  ('/fragments/frag_jomok12.webp', 'Tertawa Tapi Terluka😂', ARRAY['Gk', 'Tertawa Tapi Terluka😂', 'Aku Nak', 'Dikira Lucu😐'], 'jomok');
