-- Auto-generated by scripts/make-blank-questions.js
-- Kolom blank_image_url menyimpan versi stiker TANPA caption,
-- dipakai sebagai soal mekanik "tebak teks stiker".
-- Jalankan setelah migration v2 (kolom blank_image_url sudah ada).

UPDATE questions SET blank_image_url = v.blank_url
FROM (VALUES
  ('/fragments/frag_jomok1.webp', '/fragments-blank/jomok1.webp'),
  ('/fragments/frag_jomok2.webp', '/fragments-blank/jomok2.webp'),
  ('/fragments/frag_jomok3.webp', '/fragments-blank/jomok3.webp'),
  ('/fragments/frag_jomok4.webp', '/fragments-blank/jomok4.webp'),
  ('/fragments/frag_jomok5.webp', '/fragments-blank/jomok5.webp'),
  ('/fragments/frag_jomok6.webp', '/fragments-blank/jomok6.webp'),
  ('/fragments/frag_jomok7.webp', '/fragments-blank/jomok7.webp'),
  ('/fragments/frag_jomok8.webp', '/fragments-blank/jomok8.webp'),
  ('/fragments/frag_jomok9.webp', '/fragments-blank/jomok9.webp'),
  ('/fragments/frag_jomok10.webp', '/fragments-blank/jomok10.webp'),
  ('/fragments/frag_jomok11.webp', '/fragments-blank/jomok11.webp'),
  ('/fragments/frag_jomok12.webp', '/fragments-blank/jomok12.webp'),
  ('/fragments/frag_jomok13.webp', '/fragments-blank/jomok13.webp'),
  ('/fragments/frag_jomok14.webp', '/fragments-blank/jomok14.webp'),
  ('/fragments/frag_jomok15.webp', '/fragments-blank/jomok15.webp'),
  ('/fragments/frag_jomok16.webp', '/fragments-blank/jomok16.webp'),
  ('/fragments/frag_jomok17.webp', '/fragments-blank/jomok17.webp'),
  ('/fragments/frag_jomok18.webp', '/fragments-blank/jomok18.webp'),
  ('/fragments/frag_jomok19.webp', '/fragments-blank/jomok19.webp'),
  ('/fragments/frag_jomok21.webp', '/fragments-blank/jomok21.webp'),
  ('/fragments/frag_jomok22.webp', '/fragments-blank/jomok22.webp'),
  ('/fragments/frag_jomok23.webp', '/fragments-blank/jomok23.webp'),
  ('/fragments/frag_jomok24.webp', '/fragments-blank/jomok24.webp'),
  ('/fragments/frag_jomok25.webp', '/fragments-blank/jomok25.webp'),
  ('/fragments/frag_jomok26.webp', '/fragments-blank/jomok26.webp'),
  ('/fragments/frag_jomok27.webp', '/fragments-blank/jomok27.webp'),
  ('/fragments/frag_jomok28.webp', '/fragments-blank/jomok28.webp'),
  ('/fragments/frag_jomok29.webp', '/fragments-blank/jomok29.webp'),
  ('/fragments/frag_jomok30.webp', '/fragments-blank/jomok30.webp'),
  ('/fragments/frag_jomok32.webp', '/fragments-blank/jomok32.webp'),
  ('/fragments/frag_jomok33.webp', '/fragments-blank/jomok33.webp'),
  ('/fragments/frag_jomok34.webp', '/fragments-blank/jomok34.webp')
) AS v(fragment_url, blank_url)
WHERE questions.fragment_url = v.fragment_url;

-- Soal yang belum punya gambar blank akan jatuh ke fragment_url,
-- jadi game tetap bisa dimainkan walau sebagian aset belum siap.
