-- Auto-generated by crop-images.js
-- Run this in your Supabase SQL Editor AFTER running schema.sql

DELETE FROM questions;

INSERT INTO questions (fragment_url, correct_answer, options, category) VALUES
  ('/fragments/frag_jomok13.webp', 'Ape tu woi', ARRAY['Halah Nyocot', 'Ape tu woi', 'Amba Remaja', 'Awas Gw Lagi Sigma'], 'suki'),
  ('/fragments/frag_jomok14.webp', 'Mas Amba', ARRAY['Ape tu woi', 'Awas Gw Lagi Sigma', 'Mas Amba', 'Amba Remaja'], 'suki'),
  ('/fragments/frag_jomok15.webp', 'Kanaratzu Katsu', ARRAY['Ape tu woi', 'Kanaratzu Katsu', 'Nak Ikot', 'Mas Amba😎'], 'suki'),
  ('/fragments/frag_jomok16.webp', 'Kontol Emosimu Kawan', ARRAY['AmbaTron', 'Ape tu woi', 'Kontol Emosimu Kawan', 'Mas Amba😎'], 'suki'),
  ('/fragments/frag_jomok17.webp', 'Awas Gw Lagi Sigma', ARRAY['Nak Ikot', 'Awas Gw Lagi Sigma', 'Mas Rusdi😎', 'Alamak'], 'suki'),
  ('/fragments/frag_jomok18.webp', 'Sebaiknya Jangan Terlalu Gegabah', ARRAY['Duh Ketahuan', 'Banyak Omong Lu Suki', 'Mas Rusdi😎', 'Sebaiknya Jangan Terlalu Gegabah'], 'suki'),
  ('/fragments/frag_jomok19.webp', 'Mas Amba😎', ARRAY['Mas Amba😎', 'Tak Bosan Bosan Aku Menunggumu', 'Kontol Emosimu Kawan', 'Awas Gw Lagi Sigma'], 'suki'),
  ('/fragments/frag_jomok23.webp', 'Mas Amba😡', ARRAY['Nak Ikot', 'Ape tu woi', 'Mas Amba😡', 'Aku Bilangin ke Polisi😡'], 'suki'),
  ('/fragments/frag_jomok21.webp', 'Banyak Omong Lu Suki', ARRAY['Awas Gw Lagi Sigma', 'AmbaTron', 'Mas Amba', 'Banyak Omong Lu Suki'], 'suki'),
  ('/fragments/frag_jomok22.webp', 'Nak Ikot', ARRAY['Nak Ikot', 'Mas Fuad Sparta', 'Sebaiknya Jangan Terlalu Gegabah', 'Mas Amba😡'], 'suki'),
  ('/fragments/frag_jomok24.webp', 'Alamak', ARRAY['Sebaiknya Jangan Terlalu Gegabah', 'Banyak Omong Lu Suki', 'Kontol Emosimu Kawan', 'Alamak'], 'suki'),
  ('/fragments/frag_jomok25.webp', 'Aku Bilangin ke Polisi😡', ARRAY['Sebaiknya Jangan Terlalu Gegabah', 'Aku Bilangin ke Polisi😡', 'Ape tu woi', 'Nak Ikot'], 'suki'),
  ('/fragments/frag_jomok26.webp', 'Duh Ketahuan', ARRAY['Ngab Owi', 'Mas Fuad Sparta', 'Duh Ketahuan', 'Awas Gw Lagi Sigma'], 'suki'),
  ('/fragments/frag_jomok27.webp', 'Tak Bosan Bosan Aku Menunggumu', ARRAY['AmbaTron', 'Alamak', 'Amba Remaja', 'Tak Bosan Bosan Aku Menunggumu'], 'suki'),
  ('/fragments/frag_jomok28.webp', 'Mas Fuad Sparta', ARRAY['Mas Amba😎', 'Sebaiknya Jangan Terlalu Gegabah', 'AmbaTron', 'Mas Fuad Sparta'], 'suki'),
  ('/fragments/frag_jomok29.webp', 'Halah Nyocot', ARRAY['Tak Bosan Bosan Aku Menunggumu', 'Halah Nyocot', 'Kontol Emosimu Kawan', 'Sebaiknya Jangan Terlalu Gegabah'], 'suki'),
  ('/fragments/frag_jomok30.webp', 'Mas Rusdi😎', ARRAY['Mas Rusdi😎', 'Mas Amba', 'Halah Nyocot', 'Ape tu woi'], 'suki'),
  ('/fragments/frag_jomok32.webp', 'Ngab Owi', ARRAY['Ngab Owi', 'Nak Ikot', 'Mas Amba😎', 'Ape tu woi'], 'suki'),
  ('/fragments/frag_jomok33.webp', 'Amba Remaja', ARRAY['Amba Remaja', 'Sebaiknya Jangan Terlalu Gegabah', 'Duh Ketahuan', 'Mas Fuad Sparta'], 'suki'),
  ('/fragments/frag_jomok34.webp', 'AmbaTron', ARRAY['Alamak', 'Mas Fuad Sparta', 'Amba Remaja', 'AmbaTron'], 'suki'),
  ('/fragments/frag_jomok1.webp', 'Bersiaplah', ARRAY['Gw Lagi Yang Kena', 'Bersiaplah', 'Aku Nak', 'Rusdi'], 'jomok'),
  ('/fragments/frag_jomok2.webp', 'Berotak Kontol', ARRAY['Aku Nak', 'Berotak Kontol', 'Rusdi', 'Dikira Lucu😐'], 'jomok'),
  ('/fragments/frag_jomok3.webp', 'Rusdi', ARRAY['Yang Nanya Siapa😂', 'Langsung Sigma Gw Bjiir😂😂', 'Rusdi', 'Gk'], 'jomok'),
  ('/fragments/frag_jomok4.webp', 'Gw Lagi Yang Kena', ARRAY['Gw Lagi Yang Kena', 'Yang Nanya Siapa😂', 'Berotak Kontol', 'Langsung Sigma Gw Bjiir😂😂'], 'jomok'),
  ('/fragments/frag_jomok5.webp', 'Langsung Sigma Gw Bjiir😂😂', ARRAY['Ada Ada Saja🤣', 'Yang Nanya Siapa😂', 'Langsung Sigma Gw Bjiir😂😂', 'Gw Lagi Yang Kena'], 'jomok'),
  ('/fragments/frag_jomok6.webp', 'Gk', ARRAY['Gk', 'Yang Nanya Siapa😂', 'Bersiaplah', 'Sedang Sibuk'], 'jomok'),
  ('/fragments/frag_jomok7.webp', 'Sedang Sibuk', ARRAY['Tertawa Tapi Terluka😂', 'Sedang Sibuk', 'Ada Ada Saja🤣', 'Gw Lagi Yang Kena'], 'jomok'),
  ('/fragments/frag_jomok8.webp', 'Aku Nak', ARRAY['Yang Nanya Siapa😂', 'Aku Nak', 'Ada Ada Saja🤣', 'Langsung Sigma Gw Bjiir😂😂'], 'jomok'),
  ('/fragments/frag_jomok9.webp', 'Yang Nanya Siapa😂', ARRAY['Aku Nak', 'Bersiaplah', 'Tertawa Tapi Terluka😂', 'Yang Nanya Siapa😂'], 'jomok'),
  ('/fragments/frag_jomok10.webp', 'Dikira Lucu😐', ARRAY['Langsung Sigma Gw Bjiir😂😂', 'Aku Nak', 'Bersiaplah', 'Dikira Lucu😐'], 'jomok'),
  ('/fragments/frag_jomok11.webp', 'Ada Ada Saja🤣', ARRAY['Langsung Sigma Gw Bjiir😂😂', 'Gw Lagi Yang Kena', 'Yang Nanya Siapa😂', 'Ada Ada Saja🤣'], 'jomok'),
  ('/fragments/frag_jomok12.webp', 'Tertawa Tapi Terluka😂', ARRAY['Rusdi', 'Gk', 'Tertawa Tapi Terluka😂', 'Berotak Kontol'], 'jomok');
